name: Hugo Build and Release

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - name: Configure Git for Github
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Dependencies
      env:
        HUGO_VERSION: 0.58.3
      run: |
        echo "installing hugo $HUGO_VERSION"
        curl -sL -o /tmp/hugo.deb \
        https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb && \
        sudo dpkg -i /tmp/hugo.deb && \
        rm /tmp/hugo.deb
    - name: Publish Site
      env:
        REPOSITORY: "https://${{ secrets.GITHUB_PAT }}@github.com/${{ github.repository }}.git"
      run: ./bin/publish.sh
